### PR TITLE
UI: Initialize Next.js project with NextUI in the UI folder

### PR DESCRIPTION
**Pull request by ShubhamKadam098**
Started Next.js project with NextUI in the UI folder.

### CODE REVIEW

**Comment by aadityadike** [comment]
delete the default content of nextjs.

**Comment by ShubhamKadam098** [comment]
Got it, I've removed the default content and added a navbar component for testing purposes.

**Comment by aadityadike** [comment]
> Got it, I've removed the default content and added a navbar component for testing purposes.

did you ran it,

**Comment by ShubhamKadam098** [comment]
Yes, I have removed default assets and it's running fine.

**Review by aadityadike — APPROVED** [review]

**Pull request merged**
